case-study-1:
  raw-data: "data/case-study-1/raw/bitcoin_price_13_17.csv"
  cleaned-data: "data/case-study-1/processed/cleaned_bitcoin_price_13_17.csv"
  preprocessed-data: "data/case-study-1/processed/preprocessed_bitcoin_price_13_17.csv"
  processed-train-data: "data/case-study-1/processed/processed_train.csv"
  processed-test-data: "data/case-study-1/processed/processed_test.csv"

  graphs:
    results:
      train-test-split: "graphs/case-study-1/results/train-test-split.png"
      walk-forward-val: "graphs/case-study-1/results/walk-forward-val.png"

case-study-2:
  raw-data: "data/case-study-2/raw/ac.csv"
  cleaned-data: "data/case-study-2/processed/cleaned_bitcoin_price_2.csv"
  preprocessed-data: "data/case-study-2/processed/preprocessed_bitcoin_price_2.csv"
