case_study_1:
  raw_data: "data/case_study_1/raw/bitcoin_price_13_17.csv"
  cleaned_data: "data/case_study_1/processed/cleaned_bitcoin_price_13_17.csv"
  preprocessed_data: "data/case_study_1/processed/preprocessed_bitcoin_price_13_17.csv"
  processed_train_data: "data/case_study_1/processed/processed_train.csv"
  processed_test_data: "data/case_study_1/processed/processed_test.csv"

  graphs:
    results:
      train_test_split: "graphs/case_study_1/results/train_test_split.png"
      walk_forward_val: "graphs/case_study_1/results/walk_forward_val.png"